version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  web:
    image: exittech-web
    ports:
      - ${PUBLIC_WEB_PORT}:${WEB_PORT}
  api:
    image: exittech-api
    ports:
      - ${API_PORT}:${API_PORT}

volumes:
  db:
    driver: local
